### ISSUE TITLE
CIを回す

### ISSUE THREAD

**Issue by laco0416** [asciidwango/ES6book#11]
サンプルコードのテストを常に回しておきたい

**Comment by azu** [comment]
権限貰ったのでやる

**Comment by azu** [comment]
- Travis CI
- Gitbook プレビュー用?
- gh-pagesかな

**Comment by azu** [comment]
残りは #42 #43 をCIでビルドしてpushできるようにするところ。
textlintとかESLintのレビューコメント対応もやりたい空気

**Comment by azu** [comment]
#47 でひとまずCI関連は回るようになった。
テスト、デプロイ
