### ISSUE TITLE
2016年5月27日MTG アジェンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/ES6book#30]
2016年5月27日のミーティングで事前に書いておきたいアジェンダを書いておく場所です。

**Comment by azu** [comment]
Publicになった

**Comment by laco0416** [comment]
https://github.com/asciidwango/ES6book/issues/33

**Comment by azu** [comment]
Platform statusまとめについてどこかで言及する必要があるかも?

- https://github.com/azu/browser-javascript-resource

**Comment by azu** [comment]
コードを入れたらどのECMAScriptバージョンで入ったのを返してくれるツールを書く?

**Comment by laco0416** [comment]
URLが生きてるかのチェックをする。textlintでできるらしい

**Comment by azu** [comment]
リンクをどうするか問題
リンク切れはある程度しかたないのかも。

ECMAScriptの仕様書へのリンクはどうするか?

- http://www.ecma-international.org/ecma-262/6.0/

**Comment by azu** [comment]
仕様書の具体的な場所(セクションレベル)はあんまりリンクしないで、仕様にはありますという話レベルにする。

**Comment by azu** [comment]
今後のECMAScriptのバージョンについての話で、ES2017以降の話とか、
どこで議論されてるかとかを書くようなものを設けるとよさそう。

**Comment by azu** [comment]
> 基本文法内でも細かいユースケースが必要そう

その文法とかオブジェクトに関するパターンを出す感じ

**Comment by laco0416** [comment]
`this` の説明
`function` と アロー関数の周りで出てきそう

**Comment by azu** [comment]
#24 でクロージャーとかthisの話が絡むかなー

**Comment by azu** [comment]
> リンクを貼る基準

引用した時に引用元は入れる。
追加資料としての参考サイトはどれぐらい使うかどうか?
リンクを前提とした文章を書かない ぐらいを基準とする。

**Comment by laco0416** [comment]
本文中にURLは登場しない

**Comment by azu** [comment]
> 図は何で描くのか?

書いてみてから。
好きなツールを使って後からテイスト揃える系になるかな。

> 画像の大きさ

決めるのは難しい

**Comment by azu** [comment]
> Ajaxユースケース
> 
>     https://github.com/laco0416/plain-ajax

- XHR
- Promise
- addEventListener
- trim
- Template Strings


https://github.com/yoshuawuyts/choo

**Comment by laco0416** [comment]
モジュール分けはnode.jsのユースケース側にまかせて、Ajaxの方はindex.js1枚で済ませる方が妥当っぽい

**Comment by azu** [comment]
> Node.js CLI ユースケース
> 
>     https://github.com/laco0416/plain-node-cli

- Markdownを読み込んでファイルを読みこんでMarkdownを吐き出す
- commander
- Markdwon to HTML
- コマンドライン引数
- オプション
- コマンダー
- 外部ライブラリの使い方 ℹ️ 

最終的にサンプルのコードはこのリポジトリに含める

- Nodeの説明は少し手厚くになるかも。

**Comment by laco0416** [comment]
`process` とかNode.jsでの実行環境の話もユースケースの前あたりで触れる必要がある

**Comment by laco0416** [comment]
npmライブラリの使い方は README.md を見に行くんだよという話

**Comment by laco0416** [comment]
package.jsonの中身はこうなってるっていうのはコラムでやる semverとか。

**Comment by azu** [comment]
> Todo

Todoはモジュールとかビルドとかも入ってる。
集大成的なツールになる?
module bundlerだけのツールを書いてこの書籍ではこういうのを使うけど実際はbrowserifyとかそういうツールがあるよ的な話になる?

**Comment by laco0416** [comment]
読者が常用しないようにこの本専用だとわかるようなパッケージ名にしてしまおう

**Comment by laco0416** [comment]
ユースケースの章は、読み進めていくと出来上がるような説明の仕方をする
最初に作るものの要件みたいなのをまとめて、それを実現するためのパーツを少しずつ作って組み立てていく。

**Comment by azu** [comment]
ミーティングノートを書きました #35

**Comment by azu** [comment]
ミーティングノートマージしたのでここはCloseしますー  #35

**Comment by azu** [comment]
[CSS Secrets - O'Reilly Media](http://shop.oreilly.com/product/0636920031123.do "CSS Secrets - O&#39;Reilly Media")を読んでいたけど、この本は参考リンクに全部リダイレクトを設定してた。えらいなー

http://play.csssecrets.io/
